In [60]:
import pandas as pd
import numpy as np

df = pd.read_csv('new_mahalanobis_distances.csv')

alpha = 0.963
previousValues = []

def rewardget_combined(score, previousValues):
    # reward function 1
    reward_1 = np.tanh((100 - score) / 10) * 50
    
#     # reward function 2
#     previousValues_mean = sum(previousValues[-10:]) / len(previousValues[-10:]) if previousValues else 0
#     reward_2 = 0
#     if score >= 0 and score <= 19:
#         reward_2 = 50 - (previousValues_mean / 10)
#     elif score >= 20 and score <= 39:
#         reward_2 = 40 - (previousValues_mean / 10)
#     elif score >= 40 and score <= 59:
#         reward_2 = 30 - (previousValues_mean / 10)
#     elif score >= 60 and score <= 79:
#         reward_2 = 20 - (previousValues_mean / 10)
#     elif score >= 80 and score <= 99:
#         reward_2 = 10 - (previousValues_mean / 10)
#     elif score == 100:
#         reward_2 = 0 - (previousValues_mean / 10)
#     elif score >= 101 and score <= 120:
#         reward_2 = -10 - (previousValues_mean / 10)
#     elif score >= 121 and score <= 140:
#         reward_2 = -20 - (previousValues_mean / 10)
#     elif score >= 141 and score <= 160:
#         reward_2 = -30 - (previousValues_mean / 10)
#     elif score >= 161 and score <= 180:
#         reward_2 = -40 - (previousValues_mean / 10)
#     elif score >= 181 and score <= 200:
#         reward_2 = -50 - (previousValues_mean / 10)
    
#     # weighted average reward
#     reward = alpha * reward_1 + (1 - alpha) * reward_2
    reward=reward_1
    
    return reward

def valuefind(reward, previousValue, prev_score, current_score):
    if abs(current_score - prev_score) > 100:
        currentValue = 2 * reward + alpha * previousValue
    else:
        currentValue = reward + alpha * previousValue
    return currentValue

def send_notification(message):
    return message

currentValues = []
previousValue = 0
prev_score = df.loc[0, 'score']
notification_messages = []

for i in range(len(df)):
    score = df.loc[i, 'score']
    reward = rewardget_combined(score, previousValues)
    currentValue = valuefind(reward, previousValue, prev_score, score)
    currentValues.append(currentValue)
    previousValues.append(currentValue)
    previousValue = currentValue
    prev_score = score
    
#     # Check if an attacker query has occurred or not
#     if df.loc[i, 'attack'] == 0:
#         # Reset previousValues and previousValue
#         previousValues = []
#         previousValue = 0

    if currentValue < 0:
        message = "Safe Query"
        notification_messages.append(send_notification(message))
    else:
        message = "Unsafe Query"
        notification_messages.append(send_notification(message))

df['Value'] = currentValues
df['predicted_class'] = notification_messages

df.sample(20)

           score  original_distance  actual_class        Value predicted_class
1609  154.865580          10.911544    Safe Query  -339.358819      Safe Query
1403  103.252039           8.007556    Safe Query  -557.762580      Safe Query
406    58.556565           5.492805  Unsafe Query  1340.078118    Unsafe Query
1282   92.799518           7.419454    Safe Query   -78.741592      Safe Query
1553  102.531215           7.966999    Safe Query  -569.851733      Safe Query
1837  134.809525           9.783109    Safe Query  -546.512006      Safe Query
369    45.131716           4.737469  Unsafe Query  1318.911221    Unsafe Query
988    52.831608           5.170696  Unsafe Query  1262.999549    Unsafe Query
322    42.895610           4.611656  Unsafe Query  1227.004689    Unsafe Query
660    71.719157           6.233387  Unsafe Query  1227.618333    Unsafe Query
237    66.508193           5.940197  Unsafe Query  1262.717860    Unsafe Query
1604   69.962380           6.134543    Safe Query  -142.396405      Safe Query
393    21.556665           3.411040  Unsafe Query  1336.866994    Unsafe Query
1900  140.028861          10.076770    Safe Query  -179.802825      Safe Query
930    44.846410           4.721416  Unsafe Query  1257.605130    Unsafe Query
1988  134.043154           9.739990    Safe Query  -239.652334      Safe Query
1820  125.524206           9.260679    Safe Query  -395.354745      Safe Query
124    48.938079           4.951630  Unsafe Query  1217.164409    Unsafe Query
969   105.175873           8.115798  Unsafe Query  1245.747904    Unsafe Query
327    54.713170           5.276560  Unsafe Query  1242.630842    Unsafe Query

In [61]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Load the CSV file into a DataFrame
# df = pd.read_csv('/mnt/data/shuffled2_mahalanobis_distances.csv')

# Compute the confusion matrix
conf_matrix = confusion_matrix(df['actual_class'], df['predicted_class'], labels=["Unsafe Query", "Safe Query"])

# Create a DataFrame for the confusion matrix for better visualization
conf_matrix_df = pd.DataFrame(conf_matrix, index=["Actual Unsafe Query", "Actual Safe Query"], columns=["Predicted Unsafe Query", "Predicted Safe Query"])

# # Plot the confusion matrix
# plt.figure(figsize=(10, 7))
# sns.heatmap(conf_matrix_df, annot=True, fmt='d', cmap='Blues')
# plt.ylabel('Actual Class')
# plt.xlabel('Predicted Class')
# plt.title('Confusion Matrix: Actual Class vs Predicted Class')
# plt.show()

In [62]:
print(conf_matrix_df)

                     Predicted Unsafe Query  Predicted Safe Query
Actual Unsafe Query                    1000                     0
Actual Safe Query                        47                   953