# Using Q-Learning

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('file1.csv')

alpha = 0.02
gamma = 0.1

# Initialize Q table
num_actions = 201
Q = np.zeros((num_actions,))

prev_score = df.loc[0, 'score']
currentValues = []

# reward function
def rewardget(score, previousValues):
    previousValues_mean = sum(previousValues[-10:]) / len(previousValues[-10:]) if previousValues else 0
    if score >= 0 and score <= 19:
        reward = 50 - (previousValues_mean / 10)
    elif score >= 20 and score <= 39:
        reward = 40 - (previousValues_mean / 10)
    elif score >= 40 and score <= 59:
        reward = 30 - (previousValues_mean / 10)
    elif score >= 60 and score <= 79:
        reward = 20 - (previousValues_mean / 10)
    elif score >= 80 and score <= 99:
        reward = 10 - (previousValues_mean / 10)
    elif score == 100:
        reward = 0 - (previousValues_mean / 10)
    elif score >= 101 and score <= 120:
        reward = -10 - (previousValues_mean / 10)
    elif score >= 121 and score <= 140:
        reward = -20 - (previousValues_mean / 10)
    elif score >= 141 and score <= 160:
        reward = -30 - (previousValues_mean / 10)
    elif score >= 161 and score <= 180:
        reward = -40 - (previousValues_mean / 10)
    elif score >= 181 and score <= 200:
        reward = -50 - (previousValues_mean / 10)
    return reward

# Q-learning algo
for i in range(len(df)):
    score = df.loc[i, 'score']
    reward = rewardget(score, currentValues)
    action = score
    current_Q = Q[action]
    next_Q = max(Q)  # Assume next state is the one with the maximum Q value
    new_Q = current_Q + alpha * (reward + gamma * next_Q - current_Q)
    Q[action] = new_Q
    currentValues.append(new_Q)

df['currentValues'] = currentValues

df.head(50)

    Unnamed: 0 query  score  attack  currentValues
0            0    Q1     73       0       0.400000
1            1    Q2     38       0       0.800000
2            2    Q3    128       1      -0.399600
3            3    Q4    179       1      -0.798934
4            4    Q5    173       1      -0.798401
5            5    Q6     91       0       0.201919
6            6    Q7    182       1      -0.998202
7            7    Q8    200       1      -0.997945
8            8    Q9     15       0       1.002248
9            9   Q10     84       0       0.202358
10          10   Q11     18       0       1.002282
11          11   Q12     70       0       0.402161
12          12   Q13     23       0       0.802241
13          13   Q14     60       0       0.402001
14          14   Q15    177       1      -0.798240
15          15   Q16    131       1      -0.398240
16          16   Q17    117       1      -0.198120
17          17   Q18    171       1      -0.798280
18          18   Q19     22       0       0.801680
19          19   Q20    167       1      -0.798279
20          20   Q21     98       0       0.201921
21          21   Q22    175       1      -0.797919
22          22   Q23    104       1      -0.197679
23          23   Q24    101       1      -0.197479
24          24   Q25     58       0       0.602641
25          25   Q26     27       0       0.802361
26          26   Q27    184       1      -0.997880
27          27   Q28     93       0       0.202280
28          28   Q29      6       0       1.002080
29          29   Q30    198       1      -0.997960
30          30   Q31    128       1      -0.789528
31          31   Q32    180       1      -0.797722
32          32   Q33    109       1      -0.197722
33          33   Q34    127       1      -0.397722
34          34   Q35    192       1      -0.997682
35          35   Q36     81       0       0.202638
36          36   Q37    115       1      -0.197242
37          37   Q38      7       0       1.002598
38          38   Q39     58       0       1.193027
39          39   Q40     36       0       0.802782
40          40   Q41    141       1      -0.597579
41          41   Q42    150       1      -0.597617
42          42   Q43     69       0       0.402343
43          43   Q44    174       1      -0.797777
44          44   Q45    192       1      -1.975425
45          45   Q46     55       0       0.602499
46          46   Q47    121       1      -0.397581
47          47   Q48     93       0       0.400693
48          48   Q49     32       0       0.802579
49          49   Q50     29       0       0.802657

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# seperate features
X = df[['score', 'attack']]
y = df['currentValues']

# train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
accuracy = 1 - (mse / y_test.var())
print("Accuracy:", accuracy)

Accuracy: 0.7721764463586003